name: Spark Test
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Docker Compose UP
              run: |
                docker-compose up -d --force-recreate --remove-orphans
                sleep 6
                docker logs spark_master
                docker ps

            - name: Spark Submit
              run: |
                sudo docker exec -u 0 spark_master chmod -R 777 app
                docker exec spark_master spark-submit --master spark://spark:7077 --packages org.postgresql:postgresql:42.6.0 ./app/spark_job_re.py
