name: Spark Test
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Docker Compose UP
              run: |
                docker-compose up -d --force-recreate --remove-orphans
                sleep 6
                docker logs spark_master
            
            - name: Spark Submit
              run: docker exec spark-submit --master spark://spark:7077 --jars org.postgresql:postgresql:42.6.0 /app/spark_job.py

        
          